name = "DN3"
uuid = "49b84fb5-afed-42cc-bc8b-1049f6167dbb"
version = "0.1.0"
authors = ["zterplan <zan.terplan@sentinelmarine.net>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
LinearAlgebra = "1.12.0"
SpecialFunctions = "2.8.3"
